/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouch_InstantVidz.view.Main', {
    extend: 'Ext.tab.Panel',

    alternateClassName: [
        'main'
    ],
    requires: [
        'SenchaTouch_InstantVidz.view.VidSearchField',
        'SenchaTouch_InstantVidz.view.VideoPanel'
    ],

    config: {
        tabBarPosition: 'bottom',
        fullscreen: true,
        itemId: 'main',
        layout: {
            animation: 'pop',
            type: 'card'
        },
        items: [
            {
                xtype: 'container',
                iconCls: 'home',
                title: 'Home',
                itemId: 'homeTab',
                padding: 5,
                styleHtmlContent: true,
                ui: 'dark',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'selectfield',
                        cls: [
                            'source-selectfield'
                        ],
                        itemId: 'sourceSelect',
                        required: true,
                        options: [
                            {
                                text: 'Youtube',
                                value: 'youtube'
                            },
                            {
                                text: 'Vimeo',
                                value: 'vimeo'
                            },
                            {
                                text: 'DailyMotion',
                                value: 'dailymotion'
                            }
                        ]
                    },
                    {
                        xtype: 'vidsearchfield',
                        id: 'vidsearchfield',
                        itemId: 'vidsearchfield'
                    },
                    {
                        xtype: 'videopanel',
                        cls: [
                            'video-panel'
                        ]
                    },
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        itemId: 'titleBar',
                        title: 'InstantVidz'
                    }
                ]
            },
            {
                xtype: 'container',
                iconCls: 'info',
                title: 'About',
                itemId: 'aboutTab',
                styleHtmlContent: true,
                scrollable: true,
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        itemId: 'titleBar',
                        title: 'App Info'
                    }
                ]
            }
        ]
    }

});