/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SenchaTouch_InstantVidz.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            vidSearchField: '#vidsearchfield',
            videoPanel: '#videoPanel',
            sourceSelect: '#sourceSelect'
        },

        control: {
            "#vidsearchfield": {
                keyup: 'onSearchfieldKeyup'
            },
            "container#aboutTab": {
                activate: 'onAboutTabActivate'
            },
            "selectfield#sourceSelect": {
                change: 'onSourceSelectChange'
            }
        }
    },

    onSearchfieldKeyup: function(textfield, e, options) {
        var me           = this,
            searchField  = me.getVidSearchField(),
            videoPanel   = me.getVideoPanel(),
            keyword      = searchField.getValue(),
            sourceSelect = me.getSourceSelect();

        Ext.Ajax.request({
            url: 'util/util.php',
            method: 'POST',
            params: {
                keyword: encodeURIComponent(keyword),
                source: sourceSelect.getValue()
            },
            success: function(response) {
                videoPanel.setData(Ext.decode(response.responseText).Camideo.videos);
            },

            failure: function(response) {
                console.log("Curses, something terrible happened -> ", response.responseText);
            }

            //callback: function(options, success, response) {
            //    console.log( response.responseText );
            //}

        });
    },

    onAboutTabActivate: function(container, newActiveItem, oldActiveItem, options) {
        container.setHtml(''.concat(
        '<h2>SenchaTouch - InstantVidz</h2>',
        '<p>Author: <b>Chris Clerville</b></p>',
        '<p>GitHub: </p>',
        '<p>Inspired by: ytinstant.com</p>'
        )
        );
    },

    onSourceSelectChange: function(selectfield, newValue, oldValue, options) {
        var me = this,
            videoPanel = me.getVideoPanel();

        //console.log("before: ",videoPanel.getTpl());

        if(newValue == 'youtube') {
            videoPanel.setTpl(
            new Ext.XTemplate(
            '<tpl for=".">',  
            '<iframe', 
            'class="video-player"',
            'type="text/html"',
            'src="http://www.youtube.com/embed/{videoId}"', 
            'frameborder="0">',
            '</iframe>',
            '</tpl>'
            )
            );

        } else if(newValue === 'vimeo') {
            videoPanel.setTpl(
            new Ext.XTemplate(
            '<tpl for=".">',  
            '<iframe', 
            'class="video-player"',
            'type="text/html"',
            'src="http://player.vimeo.com/video/{videoId}"', 
            'frameborder="0" webkitAllowFullScreen allowFullScreen >',
            '</iframe>',
            '</tpl>'
            )
            );
        } else if(newValue === 'dailymotion') {
            videoPanel.setTpl(
            new Ext.XTemplate(
            '<tpl for=".">',  
            '<iframe', 
            'class="video-player"',
            'type="text/html"',
            'src="http://www.dailymotion.com/swf/{videoId}"', 
            'frameborder="0">',
            '</iframe>',
            '</tpl>'
            )
            );
        }
        //console.log("after: ",videoPanel.getTpl());
    }

});